apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: weekplanner
  labels:
    app: mongo-express
spec:
  replicas:  1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      namespace: weekplanner
      annotations:
        metrics.dynatrace.com/path: /stats/prometheus
        metrics.dynatrace.com/port: "15020"
        metrics.dynatrace.com/scrape: "true"
        metrics.dynatrace.com/secure: "false"
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: weekplanner-secret
                  key: mongo-user-name
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: weekplanner-secret
                  key: mongo-user-pass
            - name: ME_CONFIG_MONGODB_ADMINPASS_ESC
              valueFrom:
                secretKeyRef:
                  name: weekplanner-secret
                  key: mongo-user-pass-esc
            - name: ME_CONFIG_MONGODB_URL
              value: mongodb://$(ME_CONFIG_MONGODB_ADMINUSERNAME):$(ME_CONFIG_MONGODB_ADMINPASS_ESC)@mongo-service:27017/
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: weekplanner
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 31308
